import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "EN" | "PT" | "ES";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    search: "Search",
    login: "Login",
    bag: "Bag",
    categories: "Categories",
    items: "Items",
    brands: "Brands",
    designers: "Designers",
    sort: "Sort",
    sale: "Sale",
    clear: "Clear",
    clear_all: "Clear All",
    apply: "Apply",
    close: "Close",
    all_products: "All Products",
    no_products: "No products found.",
    we_dont_have_yet: "I couldn't find",
    no_results_for: "We couldn't find any results for",
    in_category: "in",
    sale_items: "sale items",
    try_searching: "Try searching with different keywords or filters.",
    search_again: "Search again",
    or: "or",
    clear_all_filters: "Clear all filters",
    cant_find: "Can't find what you're looking for?",
    suggest_product: "Request a Product",
    suggest_product_desc: "Tell us which product you'd like to see in our catalog.",
    suggest_site: "Send Feedback",
    suggest_site_desc: "Share ideas to improve your experience.",
    product_name_placeholder: "Product name",
    product_brand_placeholder: "Brand",
    your_suggestion_placeholder: "Your suggestion...",
    your_email_placeholder: "Your email (optional)",
    send_suggestion: "Send",
    suggestion_sent: "Thank you! We received your suggestion.",
    suggestion_sent_product: "Thank you! We'll look into adding this product.",
    latest: "Latest Arrivals",
    price_asc: "Price: Low to High",
    price_desc: "Price: High to Low",
    rated: "Top Rated",
    footer_tagline: "Curated luxury. Timeless pieces for the considered wardrobe.",
    shop: "Shop",
    help: "Help",
    news: "News",
    news_desc: "Receive our editorial monthly.",
    join: "Join",
    admin_portal: "Admin Portal",
    made_with_care: "Made with care",
    enter_catalog: "Enter Catalog",
    click_to_begin: "Click to Begin",
    side_a: "Side A",
    clothing: "Clothing",
    accessories: "Accessories",
    footwear: "Footwear",
    bags: "Bags",
    jewelry: "Jewelry",
    caps: "Caps",
    jackets: "Jackets",
    objects: "Objects",
    pants: "Pants",
    polo: "Polo",
    set: "Set",
    shorts: "Shorts",
    "t-shirt": "T-Shirt",
    "tank top": "Tank Top",
    hoodies: "Hoodies",
    vest: "Vest",
    product: "Product",
    products: "Products",
    back_to_catalog: "Back to Catalog",
    description: "Description",
    default_description: "The {product} reflects the essence of {designer}'s minimalist design philosophy. Crafted with premium materials and a focus on essential details, it offers both timeless style and exceptional comfort.",
    select_size: "Select a Size",
    quantity: "Quantity",
    add_to_bag: "Add to Bag",
    add_to_favorites: "Add to Favorites",
    added_to_favorites: "Go to favorites",
    proceed_to_checkout: "Proceed to Checkout",
    free_shipping: "Free shipping on orders over $100.",
    // Search bar
    search_placeholder: "products, colors...",
    // Community Looks / ALTA
    ai_stylist_tagline: "Your personal AI stylist that truly gets you",
    create_your_own: "Create Your Own",
    design_look_alta: "Design your perfect look with ALTA",
    shop_this_look: "Shop This Look",
    shop_the_look: "Shop the Look",
    total_value: "Total Value",
    add_entire_look: "Add Entire Look To Cart",
    // Cart page
    shopping_bag: "Shopping Bag",
    bag_empty: "Your shopping bag is empty.",
    continue_shopping: "Continue Shopping",
    item: "Item",
    total: "Total",
    move_to_wishlist: "Move to Wishlist",
    remove: "Remove",
    shipping_estimate: "Shipping estimate",
    calculated_at_checkout: "Calculated at Checkout",
    duties_and_taxes: "Duties and taxes",
    included: "Included",
    order_total: "Order Total",
    add_popular_items: "Add These Popular Items",
    // Cart footer
    secure_payment: "Secure Payment",
    customer_care: "Customer Care",
    location: "Location",
    editorial_archive: "Editorial Archive",
    careers: "Careers",
    country_region: "Country/Region: Brazil",
    email_signup: "Email Signup",
    affiliates: "Affiliates",
    sitemap: "Sitemap",
    terms_conditions: "Terms & Conditions",
    privacy_policy: "Privacy Policy",
    cookies: "Cookies",
    accessibility: "Accessibility",
    // Checkout page
    checkout: "Checkout",
    checkout_email_prompt: "Enter your email to login or continue to checkout as a guest.",
    email_address: "Email address",
    shipping_address: "Shipping Address",
    first_name: "First Name",
    last_name: "Last Name",
    street_address: "Street Address",
    company_optional: "Company (Optional)",
    city: "City",
    zip_code: "ZIP or Postal Code",
    country_region_label: "Country/Region",
    state_province: "State/Province",
    phone: "Phone",
    shipping_method: "Shipping Method",
    free_shipping_eligible: "Your order is eligible for free shipping.",
    standard_shipping: "Standard Shipping",
    business_days: "3-5 business days",
    free: "Free",
    payment_method: "Payment Method",
    credit_debit_card: "Credit / Debit Card",
    secure_payment_note: "All transactions are secure and encrypted.",
    card_number: "Card Number",
    name_on_card: "Name on Card",
    expiration_date: "Expiration Date (MM/YY)",
    security_code: "Security Code (CVV)",
    order_summary: "Order Summary",
    items_label: "Items",
    cart_empty: "Your cart is empty.",
    only_remaining: "Only 1 remaining",
    subtotal: "Subtotal",
    shipping_total: "Shipping Total",
    place_order: "Place Order",
    live_assistance: "Live Assistance",
    order_placed: "Order placed successfully!",
    // Footer help links
    shipping: "Shipping",
    returns: "Returns",
    contact: "Contact",
    // Onboarding
    onboarding_luxury: "Luxury curation. Restricted access.",
    onboarding_request_access: "Request Access",
    onboarding_take_quick_tour: "Take a quick tour 💫",
    onboarding_already_member: "I'm already a member ♟️",
    onboarding_first_name_title: "Enter your first name ✍️",
    onboarding_first_name_desc: "This will be used to personalize your curation.",
    onboarding_first_name_placeholder: "First name",
    onboarding_continue: "Continue",
    onboarding_lang_title: "Preferred language",
    onboarding_lang_desc: "How should we communicate with you?",
    onboarding_style_title: "Style Profile",
    onboarding_style_desc: "{name}, how do you prefer your fit?",
    onboarding_male: "Male",
    onboarding_female: "Female",
    onboarding_both: "Both",
    onboarding_hunt_title: "The Hunt",
    onboarding_hunt_desc: "And {name}, what catches your eye the most?",
    onboarding_brand_title: "Brand Affinity",
    onboarding_brand_desc: "Tell me, which of these do you like the most?",
    onboarding_email_title: "Great! Now save your email and password.",
    onboarding_email_desc: "To secure your profile and request access.",
    onboarding_email_placeholder: "Email address",
    onboarding_password_placeholder: "Password",
    onboarding_analyzing: "Analyzing profile...",
    onboarding_curating: "Curating exclusive catalog...",
    onboarding_approved: "Access Approved",
    onboarding_welcome_club: "Welcome to the club,",
    onboarding_verify_title: "Verify Your Email",
    onboarding_verify_desc1: "We've sent a verification link to",
    onboarding_verify_desc2: "Please check your inbox (and spam folder) to verify your account before logging in.",
    onboarding_redirecting: "Redirecting to login...",
    install_app_title: "Villaoro on your Home Screen",
    install_app_subtitle: "Turn Villaoro into an app ✨",
    install_step1_title: "1. Open options menu",
    install_step1_desc: "Click on share. If you don't have this option, click the three dots (⋮).",
    install_step2_title: "2. Add to Home Screen",
    install_step2_desc: "Find and click 'Add to Home Screen' or 'Install App'.",
    install_step3_title: "3. Confirm and start",
    install_step3_desc: "Confirm the name and click 'Add' or 'Install' to place the icon.",
    tour_step1_title: "Search & Filters",
    tour_step1_desc: "Find what you want quickly using the search bar, color grading, or brand selector.",
    tour_step2_title: "Product Details",
    tour_step2_desc: "Click on any product to see more photos, sizes, and add it to your favorites.",
    tour_step3_title: "Categories",
    tour_step3_desc: "Swipe and select to discover the different types of items we have for you.",
    tour_next: "Next",
    tour_done: "Done",
    install_app_tip: "💡 PWA Tip: Using 'Install App' opens Villaoro in full-screen. On iOS Chrome, if the option isn't visible, please use Safari.",
    install_app_continue: "Continue",
  },
  PT: {
    search: "Pesquisar",
    login: "Entrar",
    bag: "Sacola",
    categories: "Categorias",
    items: "Itens",
    brands: "Marcas",
    designers: "Designers",
    sort: "Ordenar",
    sale: "Promoção",
    clear: "Limpar",
    clear_all: "Limpar Tudo",
    apply: "Aplicar",
    close: "Fechar",
    all_products: "Todos os Produtos",
    no_products: "Nenhum produto encontrado.",
    we_dont_have_yet: "ainda não encontrei",
    no_results_for: "Não encontramos resultados para",
    in_category: "em",
    sale_items: "itens em promoção",
    try_searching: "Tente pesquisar com palavras-chave ou filtros diferentes.",
    search_again: "Pesquisar novamente",
    or: "ou",
    clear_all_filters: "Limpar todos os filtros",
    cant_find: "Não encontrou o que procurava?",
    suggest_product: "Solicitar Produto",
    suggest_product_desc: "Diga qual produto você gostaria de ver em nosso catálogo.",
    suggest_site: "Enviar Feedback",
    suggest_site_desc: "Compartilhe ideias para melhorar sua experiência.",
    product_name_placeholder: "Nome do produto",
    product_brand_placeholder: "Marca",
    your_suggestion_placeholder: "Sua sugestão...",
    your_email_placeholder: "Seu e-mail (opcional)",
    send_suggestion: "Enviar",
    suggestion_sent: "Obrigado! Recebemos sua sugestão.",
    suggestion_sent_product: "Obrigado! Vamos avaliar a adição deste produto.",
    latest: "Novidades",
    price_asc: "Preço: Menor",
    price_desc: "Preço: Maior",
    rated: "Mais Avaliados",
    footer_tagline: "Luxo curado. Peças atemporais para o guarda-roupa ponderado.",
    shop: "Loja",
    help: "Ajuda",
    news: "News",
    news_desc: "Receba nosso editorial mensal.",
    join: "Assinar",
    admin_portal: "Portal Admin",
    made_with_care: "Feito com cuidado",
    enter_catalog: "Entrar no Catálogo",
    click_to_begin: "Clique para Começar",
    side_a: "Lado A",
    clothing: "Vestuário",
    accessories: "Acessórios",
    footwear: "Calçados",
    bags: "Bolsas",
    jewelry: "Joalheria",
    caps: "Bonés",
    jackets: "Jaquetas",
    objects: "Objetos",
    pants: "Calças",
    polo: "Polo",
    set: "Conjuntos",
    shorts: "Shorts",
    "t-shirt": "Camisetas",
    "tank top": "Regatas",
    hoodies: "Moletons",
    vest: "Coletes",
    product: "Produto",
    products: "Produtos",
    "adidas Originals Edition Chavarria Superstar Sneakers": "Tênis adidas Originals Edição Chavarria Superstar",
    "adidas Originals Edition Karintha OG Sneakers": "Tênis adidas Originals Edição Karintha OG",
    "Salomon Edition XA Pro 3D Sneakers": "Tênis Salomon Edição XA Pro 3D",
    "Navy Croc-Embossed Ankle Boots": "Botas de Cano Curto Azul Marinho com Relevo de Crocodilo",
    "Brunello Cucinelle Brown Slides with buckles": "Chinelos Brunello Cucinelli Marrom com Fivelas",
    "Brunello Cucinelle Slides with buckles": "Chinelos Brunello Cucinelli com Fivelas",
    "Zegna Blackout Triple Stitch Sneakers": "Tênis Zegna Blackout Triple Stitch",
    "Zegna Brown Triple Stitch Sneakers": "Tênis Zegna Marrom Triple Stitch",
    "Cashmere Crewneck Sweater": "Suéter de Cashmere Gola Careca",
    "Soft Leather Tote Bag": "Bolsa Tote de Couro Macio",
    "Gold Curb Chain Bracelet": "Pulseira de Corrente de Elos em Ouro",
    "Classic Leather Belt": "Cinto de Couro Clássico",
    "Black Cotton Polo": "Polo de Algodão Preta",
    "White Cotton Polo": "Polo de Algodão Branca",
    "White Bonded nylon reversible outerwear jacket": "Jaqueta Reversível de Nylon Colado Branca",
    "Brown Flight Jacket shearling-trimmed cashmere blouson": "Blusão de Cashmere Aviador Marrom com Acabamento em Pele de Carneiro",
    back_to_catalog: "Voltar ao Catálogo",
    description: "Descrição",
    default_description: "O {product} reflete a essência da filosofia de design minimalista de {designer}. Criado com materiais premium e foco em detalhes essenciais, oferece estilo atemporal e conforto excepcional.",
    select_size: "Selecione um Tamanho",
    quantity: "Quantidade",
    add_to_bag: "Adicionar à Sacola",
    add_to_favorites: "Adicionar aos Favoritos",
    added_to_favorites: "Ir aos favoritos",
    proceed_to_checkout: "Proceder para o Checkout",
    free_shipping: "Frete grátis em pedidos acima de $100.",
    // Search bar
    search_placeholder: "produtos, cores...",
    // Community Looks / ALTA
    ai_stylist_tagline: "Seu estilista pessoal de IA que realmente te entende",
    create_your_own: "Crie o Seu",
    design_look_alta: "Crie seu look perfeito com ALTA",
    shop_this_look: "Comprar Este Look",
    shop_the_look: "Comprar o Look",
    total_value: "Valor Total",
    add_entire_look: "Adicionar Look Completo ao Carrinho",
    // Cart page
    shopping_bag: "Sacola de Compras",
    bag_empty: "Sua sacola de compras está vazia.",
    continue_shopping: "Continuar Comprando",
    item: "Item",
    total: "Total",
    move_to_wishlist: "Mover para Lista de Desejos",
    remove: "Remover",
    shipping_estimate: "Estimativa de envio",
    calculated_at_checkout: "Calculado no Checkout",
    duties_and_taxes: "Impostos e taxas",
    included: "Incluído",
    order_total: "Total do Pedido",
    add_popular_items: "Adicione Estes Itens Populares",
    // Cart footer
    secure_payment: "Pagamento Seguro",
    customer_care: "Atendimento ao Cliente",
    location: "Localização",
    editorial_archive: "Arquivo Editorial",
    careers: "Carreiras",
    country_region: "País/Região: Brasil",
    email_signup: "Cadastro de E-mail",
    affiliates: "Afiliados",
    sitemap: "Mapa do Site",
    terms_conditions: "Termos e Condições",
    privacy_policy: "Política de Privacidade",
    cookies: "Cookies",
    accessibility: "Acessibilidade",
    // Checkout page
    checkout: "Finalizar Compra",
    checkout_email_prompt: "Insira seu e-mail para fazer login ou continuar como visitante.",
    email_address: "Endereço de e-mail",
    shipping_address: "Endereço de Entrega",
    first_name: "Nome",
    last_name: "Sobrenome",
    street_address: "Endereço",
    company_optional: "Empresa (Opcional)",
    city: "Cidade",
    zip_code: "CEP",
    country_region_label: "País/Região",
    state_province: "Estado",
    phone: "Telefone",
    shipping_method: "Método de Envio",
    free_shipping_eligible: "Seu pedido tem frete grátis.",
    standard_shipping: "Envio Padrão",
    business_days: "3-5 dias úteis",
    free: "Grátis",
    payment_method: "Método de Pagamento",
    credit_debit_card: "Cartão de Crédito / Débito",
    secure_payment_note: "Todas as transações são seguras e criptografadas.",
    card_number: "Número do Cartão",
    name_on_card: "Nome no Cartão",
    expiration_date: "Data de Validade (MM/AA)",
    security_code: "Código de Segurança (CVV)",
    order_summary: "Resumo do Pedido",
    items_label: "Itens",
    cart_empty: "Seu carrinho está vazio.",
    only_remaining: "Apenas 1 restante",
    subtotal: "Subtotal",
    shipping_total: "Total de Envio",
    place_order: "Finalizar Pedido",
    live_assistance: "Assistência ao Vivo",
    order_placed: "Pedido realizado com sucesso!",
    // Footer help links
    shipping: "Envio",
    returns: "Devoluções",
    contact: "Contato",
    // Onboarding
    onboarding_luxury: "Curadoria de luxo. Acesso restrito.",
    onboarding_request_access: "Solicitar Acesso",
    onboarding_take_quick_tour: "Fazer um tour rápido 💫",
    onboarding_already_member: "Já sou um membro ♟️",
    onboarding_first_name_title: "Insira seu primeiro nome ✍️",
    onboarding_first_name_desc: "Isso será usado para personalizar sua curadoria.",
    onboarding_first_name_placeholder: "Primeiro nome",
    onboarding_continue: "Continuar",
    onboarding_lang_title: "Idioma preferido",
    onboarding_lang_desc: "Como devemos nos comunicar com você?",
    onboarding_style_title: "Perfil de Estilo",
    onboarding_style_desc: "{name}, como você prefere seu caimento?",
    onboarding_male: "Masculino",
    onboarding_female: "Feminino",
    onboarding_both: "Ambos",
    onboarding_hunt_title: "A Busca",
    onboarding_hunt_desc: "E {name}, o que mais te chama atenção?",
    onboarding_brand_title: "Afinidade de Marca",
    onboarding_brand_desc: "Me conta aqui, quais dessas você mais gosta ?",
    onboarding_email_title: "Boa! 🥳 Agora salve seu email e senha.",
    onboarding_email_desc: "Para proteger seu perfil e solicitar acesso.",
    onboarding_email_placeholder: "Endereço de e-mail",
    onboarding_password_placeholder: "Senha",
    onboarding_analyzing: "Analisando perfil...",
    onboarding_curating: "Curando catálogo exclusivo...",
    onboarding_approved: "Acesso Aprovado",
    onboarding_welcome_club: "Bem-vindo ao clube,",
    onboarding_verify_title: "Verifique seu E-mail",
    onboarding_verify_desc1: "Enviamos um link de verificação para",
    onboarding_verify_desc2: "Verifique sua caixa de entrada (e pasta de spam) para verificar sua conta antes de fazer login.",
    onboarding_redirecting: "Redirecionando para login...",
    install_app_title: "Villaoro na Tela de Início",
    install_app_subtitle: "Transforme Villaoro em um aplicativo ✨",
    install_step1_title: "1. Abra as opções do navegador",
    install_step1_desc: "Clique em compartilhar. Caso não tenha essa opção, clique nos três pontos (⋮).",
    install_step2_title: "2. Clique em Adicionar ou Instalar",
    install_step2_desc: "Selecione 'Adicionar à Tela de Início' ou 'Instalar aplicativo'.",
    install_step3_title: "3. Confirme para finalizar",
    install_step3_desc: "Confirme o nome e clique em 'Adicionar' ou 'Instalar' para criar o atalho.",
    tour_step1_title: "Busca e Filtros",
    tour_step1_desc: "Encontre o que deseja rapidamente pela barra de pesquisa, color grading ou selecionador de marcas.",
    tour_step2_title: "Detalhes do Produto",
    tour_step2_desc: "Clique em qualquer produto para ver mais fotos, tamanhos e adicioná-lo aos Favoritos.",
    tour_step3_title: "Categorias",
    tour_step3_desc: "Deslize e selecione para descobrir os diferentes tipos de itens que temos para você.",
    tour_next: "Próximo",
    tour_done: "Concluir",
    install_app_tip: "💡 Dica: A opção 'Instalar aplicativo' abre o site em tela cheia. No iOS, se não achar a opção no Chrome, use o Safari.",
    install_app_continue: "Continuar",
  },
  ES: {
    search: "Buscar",
    login: "Acceder",
    bag: "Bolsa",
    categories: "Categorías",
    items: "Artículos",
    brands: "Marcas",
    designers: "Diseñadores",
    sort: "Ordenar",
    sale: "Rebajas",
    clear: "Limpiar",
    clear_all: "Limpiar Todo",
    apply: "Aplicar",
    close: "Cerrar",
    all_products: "Todos los Productos",
    no_products: "No se encontraron productos.",
    we_dont_have_yet: "todavía no encontré",
    no_results_for: "No pudimos encontrar resultados para",
    in_category: "en",
    sale_items: "artículos en rebajas",
    try_searching: "Intenta buscar con palabras clave o filtros diferentes.",
    search_again: "Buscar de nuevo",
    or: "o",
    clear_all_filters: "Limpiar todos los filtros",
    cant_find: "¿No encuentras lo que buscas?",
    suggest_product: "Solicitar Producto",
    suggest_product_desc: "Dinos qué producto te gustaría ver en nuestro catálogo.",
    suggest_site: "Enviar Feedback",
    suggest_site_desc: "Comparte ideas para mejorar tu experiencia.",
    product_name_placeholder: "Nombre del producto",
    product_brand_placeholder: "Marca",
    your_suggestion_placeholder: "Tu sugerencia...",
    your_email_placeholder: "Tu email (opcional)",
    send_suggestion: "Enviar",
    suggestion_sent: "¡Gracias! Recibimos tu sugerencia.",
    suggestion_sent_product: "¡Gracias! Evaluaremos añadir este producto.",
    latest: "Novedades",
    price_asc: "Precio: Menor",
    price_desc: "Precio: Mayor",
    rated: "Más Valorados",
    footer_tagline: "Lujo curado. Piezas atemporales para el armario considerado.",
    shop: "Tienda",
    help: "Ayuda",
    news: "notícias",
    news_desc: "Reciba nuestro editorial mensual.",
    join: "Unirse",
    admin_portal: "Portal Admin",
    made_with_care: "Hecho con cuidado",
    enter_catalog: "Entrar al Catálogo",
    click_to_begin: "Haz clic para comenzar",
    side_a: "Lado A",
    clothing: "Ropa",
    accessories: "Accesorios",
    footwear: "Calzado",
    bags: "Bolsos",
    jewelry: "Joyería",
    caps: "Gorras",
    jackets: "Chaquetas",
    objects: "Objetos",
    pants: "Pantalones",
    polo: "Polo",
    set: "Conjuntos",
    shorts: "Pantalones Cortos",
    "t-shirt": "Camisetas",
    "tank top": "Camisetas sin mangas",
    hoodies: "Sudaderas",
    vest: "Chalecos",
    product: "Producto",
    products: "Productos",
    "adidas Originals Edition Chavarria Superstar Sneakers": "Zapatillas adidas Originals Edición Chavarria Superstar",
    "adidas Originals Edition Karintha OG Sneakers": "Zapatillas adidas Originals Edición Karintha OG",
    "Salomon Edition XA Pro 3D Sneakers": "Zapatillas Salomon Edición XA Pro 3D",
    "Navy Croc-Embossed Ankle Boots": "Botines Azul Marino con Relieve de Cocodrilo",
    "Brunello Cucinelle Brown Slides with buckles": "Sandalias Brunello Cucinelli Marrones con Hebillas",
    "Brunello Cucinelle Slides with buckles": "Sandalias Brunello Cucinelli con Hebillas",
    "Zegna Blackout Triple Stitch Sneakers": "Zapatillas Zegna Blackout Triple Stitch",
    "Zegna Brown Triple Stitch Sneakers": "Zapatillas Zegna Marrones Triple Stitch",
    "Cashmere Crewneck Sweater": "Suéter de Cachemira de Cuello Redondo",
    "Soft Leather Tote Bag": "Bolso Tote de Cuero Suave",
    "Gold Curb Chain Bracelet": "Pulsera de Cadena de Eslabones de Oro",
    "Classic Leather Belt": "Cinturón de Cuero Clásico",
    "Black Cotton Polo": "Polo de Algodón Negro",
    "White Cotton Polo": "Polo de Algodón Blanco",
    "White Bonded nylon reversible outerwear jacket": "Chaqueta Reversible de Nailon Unido Blanca",
    "Brown Flight Jacket shearling-trimmed cashmere blouson": "Cazadora de Cachemira Aviador Marrón con Ribete de Piel de Oveja",
    back_to_catalog: "Volver al Catálogo",
    description: "Descripción",
    default_description: "El {product} refleja la esencia de la filosofía de design minimalista de {designer}. Creado con materiales de primera calidad y un enfoque en los detalles esenciales, ofrece un estilo atemporal y una comodidad excepcional.",
    select_size: "Seleccione un Tamaño",
    quantity: "Cantidad",
    add_to_bag: "Añadir a la Bolsa",
    add_to_favorites: "Añadir a Favoritos",
    added_to_favorites: "Ir a favoritos",
    proceed_to_checkout: "Proceder al Checkout",
    free_shipping: "Envío gratis en pedidos superiores a $100.",
    // Search bar
    search_placeholder: "productos, colores...",
    // Community Looks / ALTA
    ai_stylist_tagline: "Tu estilista personal de IA que realmente te entiende",
    create_your_own: "Crea el Tuyo",
    design_look_alta: "Diseña tu look perfecto con ALTA",
    shop_this_look: "Comprar Este Look",
    shop_the_look: "Comprar el Look",
    total_value: "Valor Total",
    add_entire_look: "Añadir Look Completo al Carrito",
    // Cart page
    shopping_bag: "Bolsa de Compras",
    bag_empty: "Tu bolsa de compras está vacía.",
    continue_shopping: "Continuar Comprando",
    item: "Artículo",
    total: "Total",
    move_to_wishlist: "Mover a Lista de Deseos",
    remove: "Eliminar",
    shipping_estimate: "Estimación de envío",
    calculated_at_checkout: "Calculado en el Checkout",
    duties_and_taxes: "Impuestos y aranceles",
    included: "Incluido",
    order_total: "Total del Pedido",
    add_popular_items: "Añade Estos Artículos Populares",
    // Cart footer
    secure_payment: "Pago Seguro",
    customer_care: "Atención al Cliente",
    location: "Ubicación",
    editorial_archive: "Archivo Editorial",
    careers: "Carreras",
    country_region: "País/Región: Brasil",
    email_signup: "Suscripción por E-mail",
    affiliates: "Afiliados",
    sitemap: "Mapa del Sitio",
    terms_conditions: "Términos y Condiciones",
    privacy_policy: "Política de Privacidad",
    cookies: "Cookies",
    accessibility: "Accesibilidad",
    // Checkout page
    checkout: "Pagar",
    checkout_email_prompt: "Ingresa tu correo electrónico para iniciar sesión o continuar como invitado.",
    email_address: "Dirección de correo electrónico",
    shipping_address: "Dirección de Envío",
    first_name: "Nombre",
    last_name: "Apellido",
    street_address: "Dirección",
    company_optional: "Empresa (Opcional)",
    city: "Ciudad",
    zip_code: "Código Postal",
    country_region_label: "País/Región",
    state_province: "Estado/Provincia",
    phone: "Teléfono",
    shipping_method: "Método de Envío",
    free_shipping_eligible: "Tu pedido califica para envío gratis.",
    standard_shipping: "Envío Estándar",
    business_days: "3-5 días hábiles",
    free: "Gratis",
    payment_method: "Método de Pago",
    credit_debit_card: "Tarjeta de Crédito / Débito",
    secure_payment_note: "Todas las transacciones son seguras y encriptadas.",
    card_number: "Número de Tarjeta",
    name_on_card: "Nombre en la Tarjeta",
    expiration_date: "Fecha de Vencimiento (MM/AA)",
    security_code: "Código de Seguridad (CVV)",
    order_summary: "Resumen del Pedido",
    items_label: "Artículos",
    cart_empty: "Tu carrito está vacío.",
    only_remaining: "Solo queda 1",
    subtotal: "Subtotal",
    shipping_total: "Total de Envío",
    place_order: "Realizar Pedido",
    live_assistance: "Asistencia en Vivo",
    order_placed: "¡Pedido realizado con éxito!",
    // Footer help links
    shipping: "Envío",
    returns: "Devoluciones",
    contact: "Contacto",
    // Onboarding
    onboarding_luxury: "Curaduría de lujo. Acceso restringido.",
    onboarding_request_access: "Solicitar Acceso",
    onboarding_take_quick_tour: "Hacer un recorrido rápido 💫",
    onboarding_already_member: "Ya soy un miembro ♟️",
    onboarding_first_name_title: "Ingresa tu primer nombre ✍️",
    onboarding_first_name_desc: "Esto se usará para personalizar tu curaduría.",
    onboarding_first_name_placeholder: "Primer nombre",
    onboarding_continue: "Continuar",
    onboarding_lang_title: "Idioma preferido",
    onboarding_lang_desc: "¿Cómo debemos comunicarnos contigo?",
    onboarding_style_title: "Perfil de Estilo",
    onboarding_style_desc: "{name}, ¿cómo prefieres tu ajuste?",
    onboarding_male: "Masculino",
    onboarding_female: "Femenino",
    onboarding_both: "Ambos",
    onboarding_hunt_title: "La Búsqueda",
    onboarding_hunt_desc: "Y {name}, ¿qué es lo que más te llama la atención?",
    onboarding_brand_title: "Afinidad de Marca",
    onboarding_brand_desc: "Cuéntame, ¿cuáles de estas te gustan más?",
    onboarding_email_title: "¡Genial! Ahora guarda tu correo y contraseña.",
    onboarding_email_desc: "Para asegurar tu perfil y solicitar acceso.",
    onboarding_email_placeholder: "Correo electrónico",
    onboarding_password_placeholder: "Contraseña",
    onboarding_analyzing: "Analizando perfil...",
    onboarding_curating: "Curando catálogo exclusivo...",
    onboarding_approved: "Acceso Aprobado",
    onboarding_welcome_club: "Bienvenido al club,",
    onboarding_verify_title: "Verifica tu Correo Electrónico",
    onboarding_verify_desc1: "Hemos enviado un enlace de verificación a",
    onboarding_verify_desc2: "Por favor revisa tu bandeja de entrada (y carpeta de spam) para verificar tu cuenta antes de iniciar sesión.",
    onboarding_redirecting: "Redirigiendo a iniciar sesión...",
    install_app_title: "Villaoro en tu Pantalla de Inicio",
    install_app_subtitle: "Convierte Villaoro en una aplicación ✨",
    install_step1_title: "1. Abre las opciones del navegador",
    install_step1_desc: "Haz clic en compartir. Si no tienes esta opción, haz clic en los tres puntos (⋮).",
    install_step2_title: "2. Haz clic en Añadir o Instalar",
    install_step2_desc: "Selecciona 'Añadir a Pantalla de Inicio' o 'Instalar aplicación'.",
    install_step3_title: "3. Confirma para finalizar",
    install_step3_desc: "Confirma el nombre y haz clic en 'Añadir' o 'Instalar' para crear el acceso directo.",
    tour_step1_title: "Búsqueda y Filtros",
    tour_step1_desc: "Encuentra lo que deseas rápidamente con la barra de búsqueda, color grading o selector de marcas.",
    tour_step2_title: "Detalles del Producto",
    tour_step2_desc: "Haz clic en cualquier producto para ver más fotos, tallas y añadirlo a Favoritos.",
    tour_step3_title: "Categorías",
    tour_step3_desc: "Desliza y selecciona para descubrir los diferentes tipos de artículos que tenemos para ti.",
    tour_next: "Siguiente",
    tour_done: "Hecho",
    install_app_tip: "💡 Consejo: La opción 'Instalar aplicación' abre el sitio a pantalla completa. En iOS, si no ves la opción en Chrome, usa Safari.",
    install_app_continue: "Continuar",
  }
};

const commonTerms: Record<string, Record<string, string>> = {
  PT: {
    retro: "retrô",
    khaki: "caqui",
    black: "preto",
    white: "branco",
    brown: "marrom",
    blue: "azul",
    green: "verde",
    red: "vermelho",
    navy: "marinho",
    grey: "cinza",
    gray: "cinza",
    leather: "couro",
    suede: "camurça",
    cotton: "algodão",
    silk: "seda",
    wool: "lã",
    cashmere: "cashmere",
    sneakers: "tênis",
    shoes: "sapatos",
    boots: "botas",
    slides: "chinelos",
    sandals: "sandálias",
    bag: "bolsa",
    tote: "tote",
    belt: "cinto",
    hat: "chapéu",
    cap: "boné",
    bracelet: "pulseira",
    necklace: "colar",
    ring: "anel",
    gold: "ouro",
    silver: "prata",
    edition: "edição",
    original: "original",
    originals: "originals",
    classic: "clássico",
    with: "com",
    buckles: "fivelas",
    stitch: "stitch",
    triple: "triplo",
    soft: "macio",
    embossed: "relevo",
    croc: "crocodilo",
    ankle: "cano curto",
    crewneck: "gola careca",
    sweater: "suéter",
    polo: "polo",
    jacket: "jaqueta",
    flight: "aviador",
    shearling: "pele de carneiro",
    trimmed: "com acabamento",
    blouson: "blusão",
    reversible: "reversível",
    outerwear: "agasalho",
    bonded: "colado",
    nylon: "nylon"
  },
  ES: {
    retro: "retro",
    khaki: "caqui",
    black: "negro",
    white: "blanco",
    brown: "marrón",
    blue: "azul",
    green: "verde",
    red: "rojo",
    navy: "marino",
    grey: "gris",
    gray: "gris",
    leather: "cuero",
    suede: "gamuza",
    cotton: "algodón",
    silk: "seda",
    wool: "lana",
    cashmere: "cachemira",
    sneakers: "zapatillas",
    shoes: "zapatos",
    boots: "botas",
    slides: "sandalias",
    sandals: "sandalias",
    bag: "bolso",
    tote: "tote",
    belt: "cinturón",
    hat: "sombrero",
    cap: "gorra",
    bracelet: "pulsera",
    necklace: "collar",
    ring: "anillo",
    gold: "oro",
    silver: "plata",
    edition: "edición",
    original: "original",
    originals: "originals",
    classic: "clásico",
    with: "con",
    buckles: "hebillas",
    stitch: "stitch",
    triple: "triple",
    soft: "suave",
    embossed: "relieve",
    croc: "cocodrilo",
    ankle: "botín",
    crewneck: "cuello redondo",
    sweater: "suéter",
    polo: "polo",
    jacket: "chaqueta",
    flight: "aviador",
    shearling: "piel de oveja",
    trimmed: "con ribete",
    blouson: "cazadora",
    reversible: "reversible",
    outerwear: "ropa de abrigo",
    bonded: "unido",
    nylon: "nailon"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("villaoro_lang");
    if (saved === "PT" || saved === "ES" || saved === "EN") return saved;

    // Auto-detect browser language
    const browserLang = navigator.language.split("-")[0].toUpperCase();
    if (browserLang === "PT") return "PT";
    if (browserLang === "ES") return "ES";
    return "EN";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("villaoro_lang", lang);
  };

  const t = (key: string) => {
    // 1. Check for exact match in full dictionary
    if (translations[language][key]) {
      return translations[language][key];
    }

    // 2. Smart Translate Fallback: Translate common words if no exact match
    if (language !== "EN" && key && typeof key === 'string' && key.includes(" ")) {
      // For Romance languages (PT, ES), the noun usually comes before the adjective.
      // E.g., "Black Cotton Polo" -> "Polo Cotton Black".
      // This simple reversal heuristic significantly improves the readability of untranslated products.
      let words = key.split(" ");
      if (language === "PT" || language === "ES") {
        words = words.reverse();
      }

      const translatedWords = words.map(word => {
        // Extract leading and trailing punctuation
        const match = word.match(/^([^a-zA-Z0-9]*)(.*?)([^a-zA-Z0-9]*)$/);
        if (!match) return word;

        const [, prefix, coreWord, suffix] = match;
        const lowerWord = coreWord.toLowerCase();
        const translated = commonTerms[language][lowerWord];

        if (translated) {
          // Preserve capitalization if original word was capitalized
          let finalTranslated = translated;
          if (coreWord.length > 0 && coreWord[0] === coreWord[0].toUpperCase()) {
            finalTranslated = translated.charAt(0).toUpperCase() + translated.slice(1);
          }
          return `${prefix}${finalTranslated}${suffix}`;
        }
        return word;
      });

      return translatedWords.join(" ");
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className="transition-opacity duration-500 ease-in-out">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
