import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "EN" | "PT" | "ES";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    search: "Search",
    login: "Login",
    bag: "Bag",
    categories: "Categories",
    items: "Items",
    // ---- Front page (scroll sections) ----
    home_hero_eyebrow: "The Villaoro edit",
    home_hero_title: "Fewer things, chosen properly.",
    home_hero_lead: "A working catalogue from the houses that still make things to last — kept small enough that everything in it is here on purpose.",
    home_hero_cta: "Enter the catalogue",
    home_hero_cta_alt: "Read the journal",
    home_hero_available: "Available now",
    home_pieces: "pieces",
    home_manifesto_eyebrow: "Our position",
    home_manifesto_title: "We choose the pieces. We stand behind them.",
    home_manifesto_lead: "Every piece here was picked by someone who would wear it. Nothing is listed to pad the catalogue, and nothing stays listed once we would no longer recommend it.",
    home_manifesto_body: "That is the whole method: buy from houses whose work holds up, check each piece against what it claims to be, and keep the catalogue small enough that we can still answer for any of it.",
    home_figures_eyebrow: "In numbers",
    home_figures_title: "Small on purpose, and counted honestly.",
    home_figure_pieces: "Pieces in the catalogue",
    home_figure_houses: "Houses represented",
    home_figure_categories: "Departments",
    home_departments_eyebrow: "Departments",
    home_departments_title: "Everything in the wardrobe. One catalogue.",
    home_departments_lead: "Pick a department and the catalogue below filters to it.",
    home_promise_eyebrow: "Why here",
    home_promise_title: "Built for people who already know what they want.",
    home_promise_1_title: "One catalogue, no noise",
    home_promise_1_body: "No sponsored rows, no endless scroll of near-identical listings. If it is here, someone decided it should be.",
    home_promise_2_title: "Checked before it is listed",
    home_promise_2_body: "Every piece is verified against what it claims to be — house, season, materials — before it reaches the catalogue.",
    home_promise_3_title: "Prices you can actually see",
    home_promise_3_body: "The price on the card is the price at checkout. Reductions are shown against what the piece was, not against an invented figure.",
    home_promise_4_title: "In stock, or gone",
    home_promise_4_body: "We would rather show you a shorter catalogue than take an order for something we cannot send.",
    home_promise_5_title: "A person, not a queue",
    home_promise_5_body: "Questions about fit, condition or delivery are answered by someone who has handled the piece.",
    home_houses_eyebrow: "The houses",
    home_houses_title: "The names we buy from, and keep buying from.",
    home_journal_eyebrow: "Just arrived",
    home_journal_title: "The most recent additions.",
    home_journal_cta: "View all",
    home_faq_eyebrow: "Questions",
    home_faq_title: "Before you ask.",
    home_faq_1_q: "Is everything authentic?",
    home_faq_1_a: "Yes. Every piece is checked against the house's own specifications before it is listed, and anything we cannot verify does not go up.",
    home_faq_2_q: "How do I know it will fit?",
    home_faq_2_a: "Each product page carries the sizes we hold. If you are between sizes or unsure how a house runs, ask us before ordering — we have the piece to hand.",
    home_faq_3_q: "When will it arrive?",
    home_faq_3_a: "Orders leave within two working days. You will get a tracking link as soon as the parcel is collected.",
    home_faq_4_q: "Can I return something?",
    home_faq_4_a: "Yes, unworn and in its original packaging. Tell us it is coming back and we will confirm the address for your country.",
    home_faq_5_q: "Why is the catalogue this small?",
    home_faq_5_a: "Because it is chosen rather than aggregated. We would rather stand behind a few hundred pieces than list thousands we have never seen.",
    home_faq_6_q: "Something else?",
    home_faq_6_a: "Ask. There is a person at the other end, and questions about a specific piece are the ones we most like getting.",
    home_closing_eyebrow: "Start here",
    home_closing_title: "Start with what you're looking for.",
    home_closing_cta: "Browse the catalogue",
    home_closing_cta_alt: "Community looks",
    brands: "Brands",
    community_looks: "Community",
    colors: "Colours",
    news_thanks: "You're on the list.",
    designers: "Designers",
    sort: "Sort",
    sale: "Sale",
    clear: "Clear",
    clear_all: "Clear All",
    apply: "Apply",
    close: "Close",
    all_products: "All Products",
    no_products: "No products found.",
    we_dont_have_yet: "I couldn't find",
    no_results_for: "We couldn't find any results for",
    in_category: "in",
    sale_items: "sale items",
    try_searching: "Try searching with different keywords or filters.",
    search_again: "Search again",
    or: "or",
    clear_all_filters: "Clear all filters",
    cant_find: "Can't find what you're looking for?",
    suggest_product: "Request a Product",
    suggest_product_desc: "Tell us which product you'd like to see in our catalog.",
    suggest_site: "Send Feedback",
    suggest_site_desc: "Share ideas to improve your experience.",
    product_name_placeholder: "Product name",
    product_brand_placeholder: "Brand",
    your_suggestion_placeholder: "Your suggestion...",
    your_email_placeholder: "Your email (optional)",
    send_suggestion: "Send",
    suggestion_sent: "Thank you! We received your suggestion.",
    suggestion_sent_product: "Thank you! We'll look into adding this product.",
    latest: "Latest Arrivals",
    price_asc: "Price: Low to High",
    price_desc: "Price: High to Low",
    rated: "Top Rated",
    footer_tagline: "Curated luxury. Timeless pieces for the considered wardrobe.",
    shop: "Shop",
    help: "Help",
    news: "News",
    news_desc: "Receive our editorial monthly.",
    join: "Join",
    admin_portal: "Admin Portal",
    made_with_care: "Made with care",
    enter_catalog: "Enter Catalog",
    click_to_begin: "Click to Begin",
    side_a: "Side A",
    clothing: "Clothing",
    accessories: "Accessories",
    footwear: "Footwear",
    bags: "Bags",
    jewelry: "Jewelry",
    caps: "Caps",
    jackets: "Jackets",
    objects: "Objects",
    pants: "Pants",
    polo: "Polo",
    set: "Set",
    shorts: "Shorts",
    "t-shirt": "T-Shirt",
    "tank top": "Tank Top",
    sweater: "Sweater",
    "puffer jacket": "Puffer Jacket",
    // ---- Onboarding: what this is ----
    about_title_muted: "We choose the pieces.",
    about_title_strong: "You keep them for years.",
    about_body_1: "Every piece is picked by someone who would wear it, from houses whose work still holds up. Nothing is listed just to fill the catalogue.",
    about_body_2: "One place, one standard. No sponsored rows, no endless scroll of near-identical listings — only what we would stand behind.",
    about_cta: "See what's inside",
    about_stat_label: "From many houses, one edit",
    about_stat_caption: "Pieces in the catalogue",
    hoodies: "Hoodies",
    vest: "Vest",
    product: "Product",
    products: "Products",
    back_to_catalog: "Back to Catalog",
    description: "Description",
    default_description: "The {product} reflects the essence of {designer}'s minimalist design philosophy. Crafted with premium materials and a focus on essential details, it offers both timeless style and exceptional comfort.",
    select_size: "Select a Size",
    quantity: "Quantity",
    add_to_bag: "Add to Bag",
    add_to_favorites: "Add to Favorites",
    added_to_favorites: "Go to favorites",
    proceed_to_checkout: "Proceed to Checkout",
    free_shipping: "Free shipping on orders over $100.",
    // Search bar
    search_placeholder: "products, colors...",
    search_help: "Search...",
    greeting_morning: "Good morning {name}!",
    greeting_afternoon: "Good afternoon {name}!",
    greeting_evening: "Good evening {name}!",
    // Community Looks / ALTA
    ai_stylist_tagline: "Your personal AI stylist that truly gets you",
    create_your_own: "Create Your Own",
    design_look_alta: "Design your perfect look with ALTA",
    shop_this_look: "Shop This Look",
    shop_the_look: "Shop the Look",
    total_value: "Total Value",
    add_entire_look: "Add Entire Look To Cart",
    // Cart page
    shopping_bag: "Shopping Bag",
    bag_empty: "Your shopping bag is empty.",
    continue_shopping: "Continue Shopping",
    item: "Item",
    total: "Total",
    move_to_wishlist: "Move to Wishlist",
    remove: "Remove",
    shipping_estimate: "Shipping estimate",
    calculated_at_checkout: "Calculated at Checkout",
    duties_and_taxes: "Duties and taxes",
    included: "Included",
    order_total: "Order Total",
    add_popular_items: "Add These Popular Items",
    // Cart footer
    secure_payment: "Secure Payment",
    customer_care: "Customer Care",
    location: "Location",
    editorial_archive: "Editorial Archive",
    careers: "Careers",
    country_region: "Country/Region: Brazil",
    email_signup: "Email Signup",
    affiliates: "Affiliates",
    sitemap: "Sitemap",
    terms_conditions: "Terms & Conditions",
    privacy_policy: "Privacy Policy",
    cookies: "Cookies",
    accessibility: "Accessibility",
    // Checkout page
    checkout: "Checkout",
    checkout_email_prompt: "Enter your email to login or continue to checkout as a guest.",
    email_address: "Email address",
    shipping_address: "Shipping Address",
    first_name: "First Name",
    last_name: "Last Name",
    street_address: "Street Address",
    company_optional: "Company (Optional)",
    city: "City",
    zip_code: "ZIP or Postal Code",
    country_region_label: "Country/Region",
    state_province: "State/Province",
    phone: "Phone",
    shipping_method: "Shipping Method",
    free_shipping_eligible: "Your order is eligible for free shipping.",
    standard_shipping: "Standard Shipping",
    business_days: "3-5 business days",
    free: "Free",
    payment_method: "Payment Method",
    credit_debit_card: "Credit / Debit Card",
    secure_payment_note: "All transactions are secure and encrypted.",
    card_number: "Card Number",
    name_on_card: "Name on Card",
    expiration_date: "Expiration Date (MM/YY)",
    security_code: "Security Code (CVV)",
    order_summary: "Order Summary",
    items_label: "Items",
    cart_empty: "Your cart is empty.",
    only_remaining: "Only 1 remaining",
    subtotal: "Subtotal",
    shipping_total: "Shipping Total",
    place_order: "Place Order",
    live_assistance: "Live Assistance",
    order_placed: "Order placed successfully!",
    // Footer help links
    shipping: "Shipping",
    returns: "Returns",
    contact: "Contact",
    // Onboarding
    onboarding_luxury: "Luxury curation. Restricted access.",
    onboarding_request_access: "Request Access",
    onboarding_take_quick_tour: "Take a quick tour 💫",
    onboarding_already_member: "I'm already a member ♟️",
    onboarding_first_name_title: "Enter your first name ✍️",
    onboarding_first_name_desc: "This will be used to personalize your curation.",
    onboarding_first_name_placeholder: "First name",
    onboarding_continue: "Continue",
    onboarding_lang_title: "Preferred language",
    onboarding_lang_desc: "How should we communicate with you?",
    scroll_to_explore: "SCROLL TO EXPLORE",
    onboarding_style_title: "Style Profile 👤",
    onboarding_style_desc: "{name}, how do you prefer your fit?",
    onboarding_male: "Male",
    onboarding_female: "Female",
    onboarding_both: "Both",
    onboarding_hunt_title: "The Hunt 🔍",
    onboarding_hunt_desc: "And {name}, what catches your eye the most?",
    onboarding_brand_title: "Brand Affinity 💎",
    onboarding_brand_desc: "Tell me, which of these do you like the most?",
    onboarding_email_title: "Great! Now save your email and password!",
    onboarding_email_desc: "To secure your profile and request access.",
    onboarding_email_placeholder: "Email address",
    onboarding_password_placeholder: "Password",
    onboarding_analyzing: "Analyzing profile...",
    onboarding_curating: "Curating exclusive catalog...",
    onboarding_printing: "Printing your pass...",
    onboarding_ticket_presents: "Villaoro presents",
    onboarding_ticket_edition: "Private catalog",
    onboarding_ticket_admit: "Admit one",
    onboarding_ticket_footnote: "Member access",
    onboarding_ticket_guest: "Guest",
    // ---- Onboarding: what members say (placeholder copy) ----
    testimonials_eyebrow: "In their words",
    testimonials_title: "What members say.",
    testimonial_1_meta: "Member since 2024",
    testimonial_1_body: "I stopped scrolling through thousands of near-identical listings. Everything here is something I would actually wear, and that alone changed how I shop.",
    testimonial_2_meta: "São Paulo",
    testimonial_2_body: "I asked about the fit before ordering and got an answer from someone who had the piece in their hands. That is not what I am used to.",
    testimonial_3_meta: "Member since 2023",
    testimonial_3_body: "The price on the card was the price at checkout, and the piece arrived exactly as described. No surprises, which is rarer than it should be.",
    testimonial_4_meta: "Lisbon",
    testimonial_4_body: "Small catalogue, high standard. I have bought four pieces and still wear all of them, which says more than any review score.",
    testimonial_5_meta: "Member since 2025",
    testimonial_5_body: "Ordered on a Monday, tracked it the same week, wore it that weekend. The whole thing was quiet and it just worked.",
    testimonial_6_meta: "Milan",
    testimonial_6_body: "What convinced me was what is not here: no sponsored rows, no fake discounts. Someone decided each piece belonged, and you can tell.",
    onboarding_approved: "Access Approved",
    onboarding_welcome_club: "Welcome to the club,",
    onboarding_verify_title: "Verify Your Email",
    onboarding_verify_desc1: "We've sent a verification link to",
    onboarding_verify_desc2: "Please check your inbox (and spam folder) to verify your account before logging in.",
    onboarding_redirecting: "Redirecting to login...",
    install_app_title: "Villaoro on your Home Screen",
    install_app_subtitle: "Turn Villaoro into an app ✨",
    install_step1_title: "1. Open options menu",
    install_step1_desc: "Click on share. If you don't have this option, click the three dots (⋮).",
    install_step2_title: "2. Add to Home Screen",
    install_step2_desc: "Find and click 'Add to Home Screen' or 'Install App'.",
    install_step3_title: "3. Confirm and start",
    install_step3_desc: "Confirm the name and click 'Add' or 'Install' to place the icon.",
    tour_step1_title: "Search & Filters",
    tour_step1_desc: "Find what you want quickly using the search bar, color grading, or brand selector.",
    tour_step2_title: "Product Details",
    tour_step2_desc: "Click on any product to see more photos, sizes, and add it to your favorites.",
    tour_step3_title: "Categories",
    tour_step3_desc: "Swipe and select to discover the different types of items we have for you.",
    product_tour_step1_title: "Product Description",
    product_tour_step1_desc: "Here you can find all the details, materials, and styling of this piece.",
    product_tour_step2_title: "Add to Favorites",
    product_tour_step2_desc: "Click here to favorite this item and proceed with the order 📫✨",
    tour_next: "Next",
    tour_done: "Done",
    install_app_tip: "💡 PWA Tip: Using 'Install App' opens Villaoro in full-screen. On iOS Chrome, if the option isn't visible, please use Safari.",
    install_app_continue: "Continue",
    // Quick tour — catalogue preview
    tour_preview_eyebrow: "A first look",
    tour_preview_title: "This is your catalogue",
    tour_preview_subtitle: "Every piece hand-picked, refreshed every week. Keep scrolling.",
    // Sign in
    login_title: "Welcome back",
    login_subtitle: "Sign in to your curated space.",
    login_cta: "Sign In",
    login_forgot_password: "Forgot password?",
    login_reset_sending: "Sending...",
    login_reset_sent: "Reset link sent. Check your inbox.",
    login_reset_needs_email: "Enter your email address first, and we'll send you a reset link.",
    login_no_account: "Don't have an account?",
    login_success: "Welcome back!",
    login_error_credentials: "That email and password don't match. Please try again.",
    login_error_unconfirmed: "Please verify your email before signing in. Check your inbox.",
    login_error_generic: "Something went wrong. Please try again.",
    login_show_password: "Show password",
    login_hide_password: "Hide password",
    login_back: "Back",
  },
  PT: {
    search: "Pesquisar",
    login: "Entrar",
    bag: "Sacola",
    categories: "Categorias",
    items: "Itens",
    // ---- Página inicial (seções de rolagem) ----
    home_hero_eyebrow: "A seleção Villaoro",
    home_hero_title: "Menos peças, escolhidas direito.",
    home_hero_lead: "Um catálogo vivo das casas que ainda fazem peças para durar — pequeno o bastante para que tudo nele esteja aqui de propósito.",
    home_hero_cta: "Entrar no catálogo",
    home_hero_cta_alt: "Ler o jornal",
    home_hero_available: "Disponível agora",
    home_pieces: "peças",
    home_manifesto_eyebrow: "Nossa posição",
    home_manifesto_title: "Nós escolhemos as peças. E respondemos por elas.",
    home_manifesto_lead: "Cada peça aqui foi escolhida por alguém que a usaria. Nada entra para encher o catálogo, e nada continua listado quando deixamos de recomendar.",
    home_manifesto_body: "O método é esse: comprar de casas cujo trabalho se sustenta, conferir cada peça contra o que ela diz ser, e manter o catálogo pequeno o bastante para respondermos por qualquer item.",
    home_figures_eyebrow: "Em números",
    home_figures_title: "Pequeno de propósito, e contado com honestidade.",
    home_figure_pieces: "Peças no catálogo",
    home_figure_houses: "Casas representadas",
    home_figure_categories: "Departamentos",
    home_departments_eyebrow: "Departamentos",
    home_departments_title: "Todo o guarda-roupa. Um catálogo.",
    home_departments_lead: "Escolha um departamento e o catálogo abaixo filtra para ele.",
    home_promise_eyebrow: "Por que aqui",
    home_promise_title: "Feito para quem já sabe o que quer.",
    home_promise_1_title: "Um catálogo, sem ruído",
    home_promise_1_body: "Sem anúncios, sem rolagem infinita de itens quase iguais. Se está aqui, alguém decidiu que deveria estar.",
    home_promise_2_title: "Conferida antes de entrar",
    home_promise_2_body: "Cada peça é verificada contra o que diz ser — casa, temporada, materiais — antes de chegar ao catálogo.",
    home_promise_3_title: "Preços que você enxerga",
    home_promise_3_body: "O preço do card é o preço do checkout. Descontos aparecem sobre o valor real anterior, não sobre um número inventado.",
    home_promise_4_title: "Em estoque, ou fora",
    home_promise_4_body: "Preferimos mostrar um catálogo menor a aceitar um pedido que não podemos enviar.",
    home_promise_5_title: "Uma pessoa, não uma fila",
    home_promise_5_body: "Dúvidas de caimento, estado ou entrega são respondidas por quem teve a peça em mãos.",
    home_houses_eyebrow: "As casas",
    home_houses_title: "Os nomes de quem compramos, e continuamos comprando.",
    home_journal_eyebrow: "Acabou de chegar",
    home_journal_title: "As adições mais recentes.",
    home_journal_cta: "Ver tudo",
    home_faq_eyebrow: "Perguntas",
    home_faq_title: "Antes de perguntar.",
    home_faq_1_q: "É tudo original?",
    home_faq_1_a: "Sim. Cada peça é conferida contra as especificações da própria casa antes de ser listada, e o que não conseguimos verificar não entra.",
    home_faq_2_q: "Como sei se vai servir?",
    home_faq_2_a: "Cada página traz os tamanhos que temos. Se você fica entre dois tamanhos ou não conhece a modelagem da casa, pergunte antes — a peça está aqui conosco.",
    home_faq_3_q: "Quando chega?",
    home_faq_3_a: "Os pedidos saem em até dois dias úteis. Você recebe o link de rastreio assim que a encomenda é coletada.",
    home_faq_4_q: "Posso devolver?",
    home_faq_4_a: "Pode, sem uso e na embalagem original. Avise que está voltando e confirmamos o endereço para o seu país.",
    home_faq_5_q: "Por que o catálogo é pequeno?",
    home_faq_5_a: "Porque ele é escolhido, não agregado. Preferimos responder por algumas centenas de peças a listar milhares que nunca vimos.",
    home_faq_6_q: "Mais alguma coisa?",
    home_faq_6_a: "Pergunte. Tem uma pessoa do outro lado, e dúvidas sobre uma peça específica são as que mais gostamos de receber.",
    home_closing_eyebrow: "Comece aqui",
    home_closing_title: "Comece pelo que você procura.",
    home_closing_cta: "Ver o catálogo",
    home_closing_cta_alt: "Looks da comunidade",
    brands: "Marcas",
    community_looks: "Comunidade",
    colors: "Cores",
    news_thanks: "Você está na lista.",
    designers: "Designers",
    sort: "Ordenar",
    sale: "Promoção",
    clear: "Limpar",
    clear_all: "Limpar Tudo",
    apply: "Aplicar",
    close: "Fechar",
    all_products: "Todos os Produtos",
    no_products: "Nenhum produto encontrado.",
    we_dont_have_yet: "ainda não encontrei",
    no_results_for: "Não encontramos resultados para",
    in_category: "em",
    sale_items: "itens em promoção",
    try_searching: "Tente pesquisar com palavras-chave ou filtros diferentes.",
    search_again: "Pesquisar novamente",
    or: "ou",
    clear_all_filters: "Limpar todos os filtros",
    cant_find: "Não encontrou o que procurava?",
    suggest_product: "Solicitar Produto",
    suggest_product_desc: "Diga qual produto você gostaria de ver em nosso catálogo.",
    suggest_site: "Enviar Feedback",
    suggest_site_desc: "Compartilhe ideias para melhorar sua experiência.",
    product_name_placeholder: "Nome do produto",
    product_brand_placeholder: "Marca",
    your_suggestion_placeholder: "Sua sugestão...",
    your_email_placeholder: "Seu e-mail (opcional)",
    send_suggestion: "Enviar",
    suggestion_sent: "Obrigado! Recebemos sua sugestão.",
    suggestion_sent_product: "Obrigado! Vamos avaliar a adição deste produto.",
    latest: "Novidades",
    price_asc: "Preço: Menor",
    price_desc: "Preço: Maior",
    rated: "Mais Avaliados",
    footer_tagline: "Luxo curado. Peças atemporais para o guarda-roupa ponderado.",
    shop: "Loja",
    help: "Ajuda",
    news: "News",
    news_desc: "Receba nosso editorial mensal.",
    join: "Assinar",
    admin_portal: "Portal Admin",
    made_with_care: "Feito com cuidado",
    enter_catalog: "Entrar no Catálogo",
    click_to_begin: "Clique para Começar",
    side_a: "Lado A",
    clothing: "Vestuário",
    accessories: "Acessórios",
    footwear: "Calçados",
    bags: "Bolsas",
    jewelry: "Joalheria",
    caps: "Bonés",
    jackets: "Jaquetas",
    objects: "Objetos",
    pants: "Calças",
    polo: "Polo",
    set: "Conjuntos",
    shorts: "Shorts",
    "t-shirt": "Camisetas",
    "tank top": "Regatas",
    "puffer jacket": "Jaqueta Puffer",
    // ---- Onboarding: o que é isto ----
    about_title_muted: "Nós escolhemos as peças.",
    about_title_strong: "Você usa por anos.",
    about_body_1: "Cada peça é escolhida por alguém que a usaria, de casas cujo trabalho se sustenta. Nada entra só para encher o catálogo.",
    about_body_2: "Um lugar, um padrão. Sem anúncios, sem rolagem infinita de itens quase iguais — só o que assumimos.",
    about_cta: "Ver o que tem dentro",
    about_stat_label: "De muitas casas, uma seleção",
    about_stat_caption: "Peças no catálogo",
    hoodies: "Moletons",
    vest: "Coletes",
    product: "Produto",
    products: "Produtos",
    "adidas Originals Edition Chavarria Superstar Sneakers": "Tênis adidas Originals Edição Chavarria Superstar",
    "adidas Originals Edition Karintha OG Sneakers": "Tênis adidas Originals Edição Karintha OG",
    "Salomon Edition XA Pro 3D Sneakers": "Tênis Salomon Edição XA Pro 3D",
    "Navy Croc-Embossed Ankle Boots": "Botas de Cano Curto Azul Marinho com Relevo de Crocodilo",
    "Brunello Cucinelle Brown Slides with buckles": "Chinelos Brunello Cucinelli Marrom com Fivelas",
    "Brunello Cucinelle Slides with buckles": "Chinelos Brunello Cucinelli com Fivelas",
    "Zegna Blackout Triple Stitch Sneakers": "Tênis Zegna Blackout Triple Stitch",
    "Zegna Brown Triple Stitch Sneakers": "Tênis Zegna Marrom Triple Stitch",
    "Cashmere Crewneck Sweater": "Suéter de Cashmere Gola Careca",
    "Soft Leather Tote Bag": "Bolsa Tote de Couro Macio",
    "Gold Curb Chain Bracelet": "Pulseira de Corrente de Elos em Ouro",
    "Classic Leather Belt": "Cinto de Couro Clássico",
    "Black Cotton Polo": "Polo de Algodão Preta",
    "White Cotton Polo": "Polo de Algodão Branca",
    "White Bonded nylon reversible outerwear jacket": "Jaqueta Reversível de Nylon Colado Branca",
    "Brown Flight Jacket shearling-trimmed cashmere blouson": "Blusão de Cashmere Aviador Marrom com Acabamento em Pele de Carneiro",
    back_to_catalog: "Voltar ao Catálogo",
    description: "Descrição",
    default_description: "O {product} reflete a essência da filosofia de design minimalista de {designer}. Criado com materiais premium e foco em detalhes essenciais, oferece estilo atemporal e conforto excepcional.",
    select_size: "Selecione um Tamanho",
    quantity: "Quantidade",
    add_to_bag: "Adicionar à Sacola",
    add_to_favorites: "Adicionar aos Favoritos",
    added_to_favorites: "Ir aos favoritos",
    proceed_to_checkout: "Proceder para o Checkout",
    free_shipping: "Frete grátis em pedidos acima de $100.",
    // Search bar
    search_placeholder: "produtos, cores...",
    search_help: "Pesquisar...",
    greeting_morning: "Bom dia {name}!",
    greeting_afternoon: "Boa tarde {name}!",
    greeting_evening: "Boa noite {name}!",
    // Community Looks / ALTA
    ai_stylist_tagline: "Seu estilista pessoal de IA que realmente te entende",
    create_your_own: "Crie o Seu",
    design_look_alta: "Crie seu look perfeito com ALTA",
    shop_this_look: "Comprar Este Look",
    shop_the_look: "Comprar o Look",
    total_value: "Valor Total",
    add_entire_look: "Adicionar Look Completo ao Carrinho",
    // Cart page
    shopping_bag: "Sacola de Compras",
    bag_empty: "Sua sacola de compras está vazia.",
    continue_shopping: "Continuar Comprando",
    item: "Item",
    total: "Total",
    move_to_wishlist: "Mover para Lista de Desejos",
    remove: "Remover",
    shipping_estimate: "Estimativa de envio",
    calculated_at_checkout: "Calculado no Checkout",
    duties_and_taxes: "Impostos e taxas",
    included: "Incluído",
    order_total: "Total do Pedido",
    add_popular_items: "Adicione Estes Itens Populares",
    // Cart footer
    secure_payment: "Pagamento Seguro",
    customer_care: "Atendimento ao Cliente",
    location: "Localização",
    editorial_archive: "Arquivo Editorial",
    careers: "Carreiras",
    country_region: "País/Região: Brasil",
    email_signup: "Cadastro de E-mail",
    affiliates: "Afiliados",
    sitemap: "Mapa do Site",
    terms_conditions: "Termos e Condições",
    privacy_policy: "Política de Privacidade",
    cookies: "Cookies",
    accessibility: "Acessibilidade",
    // Checkout page
    checkout: "Finalizar Compra",
    checkout_email_prompt: "Insira seu e-mail para fazer login ou continuar como visitante.",
    email_address: "Endereço de e-mail",
    shipping_address: "Endereço de Entrega",
    first_name: "Nome",
    last_name: "Sobrenome",
    street_address: "Endereço",
    company_optional: "Empresa (Opcional)",
    city: "Cidade",
    zip_code: "CEP",
    country_region_label: "País/Região",
    state_province: "Estado",
    phone: "Telefone",
    shipping_method: "Método de Envio",
    free_shipping_eligible: "Seu pedido tem frete grátis.",
    standard_shipping: "Envio Padrão",
    business_days: "3-5 dias úteis",
    free: "Grátis",
    payment_method: "Método de Pagamento",
    credit_debit_card: "Cartão de Crédito / Débito",
    secure_payment_note: "Todas as transações são seguras e criptografadas.",
    card_number: "Número do Cartão",
    name_on_card: "Nome no Cartão",
    expiration_date: "Data de Validade (MM/AA)",
    security_code: "Código de Segurança (CVV)",
    order_summary: "Resumo do Pedido",
    items_label: "Itens",
    cart_empty: "Seu carrinho está vazio.",
    only_remaining: "Apenas 1 restante",
    subtotal: "Subtotal",
    shipping_total: "Total de Envio",
    place_order: "Finalizar Pedido",
    live_assistance: "Assistência ao Vivo",
    order_placed: "Pedido realizado com sucesso!",
    // Footer help links
    shipping: "Envio",
    returns: "Devoluções",
    contact: "Contato",
    // Onboarding
    onboarding_luxury: "Curadoria de luxo. Acesso restrito.",
    onboarding_request_access: "Solicitar Acesso",
    onboarding_take_quick_tour: "EXPLORAR 💫",
    onboarding_already_member: "Já sou um membro ♟️",
    onboarding_first_name_title: "Insira seu primeiro nome ✍️",
    onboarding_first_name_desc: "Isso será usado para personalizar sua curadoria.",
    onboarding_first_name_placeholder: "Primeiro nome",
    onboarding_continue: "Continuar",
    onboarding_lang_title: "Idioma preferido",
    onboarding_lang_desc: "Como devemos nos comunicar com você?",
    scroll_to_explore: "DESLIZE PARA EXPLORAR",
    onboarding_style_title: "Perfil de Estilo 👤",
    onboarding_style_desc: "{name}, como você prefere seu caimento?",
    onboarding_male: "Masculino",
    onboarding_female: "Feminino",
    onboarding_both: "Ambos",
    onboarding_hunt_title: "A Busca 🔍",
    onboarding_hunt_desc: "E {name}, o que mais te chama atenção?",
    onboarding_brand_title: "Afinidade de Marca 💎",
    onboarding_brand_desc: "Me conta aqui, quais dessas você mais gosta ?",
    onboarding_email_title: "Boa! 🥳 Agora salve seu email e senha!",
    onboarding_email_desc: "Para proteger seu perfil e solicitar acesso.",
    onboarding_email_placeholder: "Endereço de e-mail",
    onboarding_password_placeholder: "Senha",
    onboarding_analyzing: "Analisando perfil...",
    onboarding_curating: "Curando catálogo exclusivo...",
    onboarding_printing: "Imprimindo seu passe...",
    onboarding_ticket_presents: "Villaoro apresenta",
    onboarding_ticket_edition: "Catálogo privado",
    onboarding_ticket_admit: "Acesso único",
    onboarding_ticket_footnote: "Acesso de membro",
    onboarding_ticket_guest: "Convidado",
    // ---- Onboarding: o que os membros dizem (texto provisório) ----
    testimonials_eyebrow: "Nas palavras deles",
    testimonials_title: "O que os membros dizem.",
    testimonial_1_meta: "Membro desde 2024",
    testimonial_1_body: "Parei de rolar milhares de anúncios quase iguais. Tudo aqui é algo que eu realmente usaria, e só isso já mudou como eu compro.",
    testimonial_2_meta: "São Paulo",
    testimonial_2_body: "Perguntei sobre o caimento antes de comprar e quem respondeu tinha a peça em mãos. Não é o que eu estou acostumada a receber.",
    testimonial_3_meta: "Membro desde 2023",
    testimonial_3_body: "O preço do card era o preço no checkout, e a peça chegou exatamente como descrita. Sem surpresas — mais raro do que deveria ser.",
    testimonial_4_meta: "Lisboa",
    testimonial_4_body: "Catálogo pequeno, padrão alto. Já comprei quatro peças e uso todas até hoje, o que diz mais do que qualquer nota.",
    testimonial_5_meta: "Membro desde 2025",
    testimonial_5_body: "Pedi na segunda, acompanhei o rastreio na mesma semana e usei no fim de semana. Foi tudo silencioso e simplesmente funcionou.",
    testimonial_6_meta: "Milão",
    testimonial_6_body: "O que me convenceu foi o que não tem aqui: sem anúncios pagos, sem desconto de mentira. Alguém decidiu que cada peça merecia estar, e dá para perceber.",
    onboarding_approved: "Acesso Aprovado",
    onboarding_welcome_club: "Bem-vindo ao clube,",
    onboarding_verify_title: "Verifique seu E-mail",
    onboarding_verify_desc1: "Enviamos um link de verificação para",
    onboarding_verify_desc2: "Verifique sua caixa de entrada (e pasta de spam) para verificar sua conta antes de fazer login.",
    onboarding_redirecting: "Redirecionando para login...",
    install_app_title: "Villaoro na Tela de Início",
    install_app_subtitle: "Transforme Villaoro em um aplicativo ✨",
    install_step1_title: "1. Abra as opções do navegador",
    install_step1_desc: "Clique em compartilhar. Caso não tenha essa opção, clique nos três pontos (⋮).",
    install_step2_title: "2. Clique em Adicionar ou Instalar",
    install_step2_desc: "Selecione 'Adicionar à Tela de Início' ou 'Instalar aplicativo'.",
    install_step3_title: "3. Confirme para finalizar",
    install_step3_desc: "Confirme o nome e clique em 'Adicionar' ou 'Instalar' para criar o atalho.",
    tour_step1_title: "Busca e Filtros",
    tour_step1_desc: "Encontre o que deseja rapidamente pela barra de pesquisa, color grading ou selecionador de marcas.",
    tour_step2_title: "Detalhes do Produto",
    tour_step2_desc: "Clique em qualquer produto para ver mais fotos, tamanhos e adicioná-lo aos Favoritos.",
    tour_step3_title: "Categorias",
    tour_step3_desc: "Deslize e selecione para descobrir os diferentes tipos de itens que temos para você.",
    product_tour_step1_title: "Descrição do Produto",
    product_tour_step1_desc: "Aqui você encontra todos os detalhes, materiais e o estilo desta peça.",
    product_tour_step2_title: "Adicionar aos Favoritos",
    product_tour_step2_desc: "Clique aqui para favoritar este item e seguir com o pedido 📫✨",
    tour_next: "Próximo",
    tour_done: "Concluir",
    install_app_tip: "💡 Dica: A opção 'Instalar aplicativo' abre o site em tela cheia. No iOS, se não achar a opção no Chrome, use o Safari.",
    install_app_continue: "Continuar",
    // Quick tour — catalogue preview
    tour_preview_eyebrow: "Uma primeira olhada",
    tour_preview_title: "Este é o seu catálogo",
    tour_preview_subtitle: "Cada peça escolhida a dedo, renovada toda semana. Continue rolando.",
    // Sign in
    login_title: "Bem-vindo de volta",
    login_subtitle: "Entre no seu espaço curado.",
    login_cta: "Entrar",
    login_forgot_password: "Esqueceu a senha?",
    login_reset_sending: "Enviando...",
    login_reset_sent: "Link de redefinição enviado. Verifique seu e-mail.",
    login_reset_needs_email: "Digite seu e-mail primeiro e enviaremos um link de redefinição.",
    login_no_account: "Ainda não tem uma conta?",
    login_success: "Bem-vindo de volta!",
    login_error_credentials: "E-mail ou senha incorretos. Tente novamente.",
    login_error_unconfirmed: "Verifique seu e-mail antes de entrar. Confira sua caixa de entrada.",
    login_error_generic: "Algo deu errado. Tente novamente.",
    login_show_password: "Mostrar senha",
    login_hide_password: "Ocultar senha",
    login_back: "Voltar",
  },
  ES: {
    search: "Buscar",
    login: "Acceder",
    bag: "Bolsa",
    categories: "Categorías",
    items: "Artículos",
    // ---- Página de inicio (secciones de desplazamiento) ----
    home_hero_eyebrow: "La selección Villaoro",
    home_hero_title: "Menos piezas, elegidas bien.",
    home_hero_lead: "Un catálogo vivo de las casas que aún hacen piezas para durar — pequeño como para que todo lo que hay esté aquí a propósito.",
    home_hero_cta: "Entrar al catálogo",
    home_hero_cta_alt: "Leer el diario",
    home_hero_available: "Disponible ahora",
    home_pieces: "piezas",
    home_manifesto_eyebrow: "Nuestra posición",
    home_manifesto_title: "Elegimos las piezas. Y respondemos por ellas.",
    home_manifesto_lead: "Cada pieza fue elegida por alguien que la usaría. Nada se publica para rellenar el catálogo, y nada sigue publicado si dejamos de recomendarlo.",
    home_manifesto_body: "El método es ese: comprar a casas cuyo trabajo aguanta, comprobar cada pieza contra lo que dice ser, y mantener el catálogo lo bastante pequeño como para responder por cualquiera.",
    home_figures_eyebrow: "En números",
    home_figures_title: "Pequeño a propósito, y contado con honestidad.",
    home_figure_pieces: "Piezas en el catálogo",
    home_figure_houses: "Casas representadas",
    home_figure_categories: "Departamentos",
    home_departments_eyebrow: "Departamentos",
    home_departments_title: "Todo el armario. Un catálogo.",
    home_departments_lead: "Elige un departamento y el catálogo de abajo se filtra.",
    home_promise_eyebrow: "Por qué aquí",
    home_promise_title: "Hecho para quien ya sabe lo que busca.",
    home_promise_1_title: "Un catálogo, sin ruido",
    home_promise_1_body: "Sin anuncios, sin scroll infinito de artículos casi idénticos. Si está aquí, alguien decidió que debía estar.",
    home_promise_2_title: "Comprobada antes de publicarse",
    home_promise_2_body: "Cada pieza se verifica contra lo que dice ser — casa, temporada, materiales — antes de llegar al catálogo.",
    home_promise_3_title: "Precios que se ven",
    home_promise_3_body: "El precio de la ficha es el del pago. Las rebajas se muestran sobre el valor real anterior, no sobre una cifra inventada.",
    home_promise_4_title: "En stock, o fuera",
    home_promise_4_body: "Preferimos enseñar un catálogo más corto que aceptar un pedido que no podemos enviar.",
    home_promise_5_title: "Una persona, no una cola",
    home_promise_5_body: "Las dudas de talla, estado o envío las responde quien ha tenido la pieza en la mano.",
    home_houses_eyebrow: "Las casas",
    home_houses_title: "Los nombres a los que compramos, y seguimos comprando.",
    home_journal_eyebrow: "Recién llegado",
    home_journal_title: "Las incorporaciones más recientes.",
    home_journal_cta: "Ver todo",
    home_faq_eyebrow: "Preguntas",
    home_faq_title: "Antes de preguntar.",
    home_faq_1_q: "¿Es todo auténtico?",
    home_faq_1_a: "Sí. Cada pieza se comprueba contra las especificaciones de la propia casa antes de publicarse, y lo que no podemos verificar no entra.",
    home_faq_2_q: "¿Cómo sé si me va a quedar?",
    home_faq_2_a: "Cada ficha lleva las tallas que tenemos. Si estás entre dos tallas o no conoces el patronaje de la casa, pregúntanos antes — tenemos la pieza aquí.",
    home_faq_3_q: "¿Cuándo llega?",
    home_faq_3_a: "Los pedidos salen en dos días laborables. Recibirás el enlace de seguimiento en cuanto se recoja el paquete.",
    home_faq_4_q: "¿Puedo devolverlo?",
    home_faq_4_a: "Sí, sin usar y en su embalaje original. Avísanos de que vuelve y te confirmamos la dirección para tu país.",
    home_faq_5_q: "¿Por qué el catálogo es tan pequeño?",
    home_faq_5_a: "Porque está elegido, no agregado. Preferimos responder por unos cientos de piezas que listar miles que no hemos visto nunca.",
    home_faq_6_q: "¿Algo más?",
    home_faq_6_a: "Pregunta. Hay una persona al otro lado, y las dudas sobre una pieza concreta son las que más nos gustan.",
    home_closing_eyebrow: "Empieza aquí",
    home_closing_title: "Empieza por lo que buscas.",
    home_closing_cta: "Ver el catálogo",
    home_closing_cta_alt: "Looks de la comunidad",
    brands: "Marcas",
    community_looks: "Comunidad",
    colors: "Colores",
    news_thanks: "Estás en la lista.",
    designers: "Diseñadores",
    sort: "Ordenar",
    sale: "Rebajas",
    clear: "Limpiar",
    clear_all: "Limpiar Todo",
    apply: "Aplicar",
    close: "Cerrar",
    all_products: "Todos los Productos",
    no_products: "No se encontraron productos.",
    we_dont_have_yet: "todavía no encontré",
    no_results_for: "No pudimos encontrar resultados para",
    in_category: "en",
    sale_items: "artículos en rebajas",
    try_searching: "Intenta buscar con palabras clave o filtros diferentes.",
    search_again: "Buscar de nuevo",
    or: "o",
    clear_all_filters: "Limpiar todos los filtros",
    cant_find: "¿No encuentras lo que buscas?",
    suggest_product: "Solicitar Producto",
    suggest_product_desc: "Dinos qué producto te gustaría ver en nuestro catálogo.",
    suggest_site: "Enviar Feedback",
    suggest_site_desc: "Comparte ideas para mejorar tu experiencia.",
    product_name_placeholder: "Nombre del producto",
    product_brand_placeholder: "Marca",
    your_suggestion_placeholder: "Tu sugerencia...",
    your_email_placeholder: "Tu email (opcional)",
    send_suggestion: "Enviar",
    suggestion_sent: "¡Gracias! Recibimos tu sugerencia.",
    suggestion_sent_product: "¡Gracias! Evaluaremos añadir este producto.",
    latest: "Novedades",
    price_asc: "Precio: Menor",
    price_desc: "Precio: Mayor",
    rated: "Más Valorados",
    footer_tagline: "Lujo curado. Piezas atemporales para el armario considerado.",
    shop: "Tienda",
    help: "Ayuda",
    news: "notícias",
    news_desc: "Reciba nuestro editorial mensual.",
    join: "Unirse",
    admin_portal: "Portal Admin",
    made_with_care: "Hecho con cuidado",
    enter_catalog: "Entrar al Catálogo",
    click_to_begin: "Haz clic para comenzar",
    side_a: "Lado A",
    clothing: "Ropa",
    accessories: "Accesorios",
    footwear: "Calzado",
    bags: "Bolsos",
    jewelry: "Joyería",
    caps: "Gorras",
    jackets: "Chaquetas",
    objects: "Objetos",
    pants: "Pantalones",
    polo: "Polo",
    set: "Conjuntos",
    shorts: "Pantalones Cortos",
    "t-shirt": "Camisetas",
    "tank top": "Camisetas sin mangas",
    "puffer jacket": "Chaqueta acolchada",
    // ---- Onboarding: qué es esto ----
    about_title_muted: "Elegimos las piezas.",
    about_title_strong: "Las usas durante años.",
    about_body_1: "Cada pieza la elige alguien que la usaría, de casas cuyo trabajo aguanta. Nada se publica solo para llenar el catálogo.",
    about_body_2: "Un lugar, un estándar. Sin anuncios, sin scroll infinito de artículos casi idénticos — solo lo que respaldamos.",
    about_cta: "Ver lo que hay dentro",
    about_stat_label: "De muchas casas, una selección",
    about_stat_caption: "Piezas en el catálogo",
    hoodies: "Sudaderas",
    vest: "Chalecos",
    product: "Producto",
    products: "Productos",
    "adidas Originals Edition Chavarria Superstar Sneakers": "Zapatillas adidas Originals Edición Chavarria Superstar",
    "adidas Originals Edition Karintha OG Sneakers": "Zapatillas adidas Originals Edición Karintha OG",
    "Salomon Edition XA Pro 3D Sneakers": "Zapatillas Salomon Edición XA Pro 3D",
    "Navy Croc-Embossed Ankle Boots": "Botines Azul Marino con Relieve de Cocodrilo",
    "Brunello Cucinelle Brown Slides with buckles": "Sandalias Brunello Cucinelli Marrones con Hebillas",
    "Brunello Cucinelle Slides with buckles": "Sandalias Brunello Cucinelli con Hebillas",
    "Zegna Blackout Triple Stitch Sneakers": "Zapatillas Zegna Blackout Triple Stitch",
    "Zegna Brown Triple Stitch Sneakers": "Zapatillas Zegna Marrones Triple Stitch",
    "Cashmere Crewneck Sweater": "Suéter de Cachemira de Cuello Redondo",
    "Soft Leather Tote Bag": "Bolso Tote de Cuero Suave",
    "Gold Curb Chain Bracelet": "Pulsera de Cadena de Eslabones de Oro",
    "Classic Leather Belt": "Cinturón de Cuero Clásico",
    "Black Cotton Polo": "Polo de Algodón Negro",
    "White Cotton Polo": "Polo de Algodón Blanco",
    "White Bonded nylon reversible outerwear jacket": "Chaqueta Reversible de Nailon Unido Blanca",
    "Brown Flight Jacket shearling-trimmed cashmere blouson": "Cazadora de Cachemira Aviador Marrón con Ribete de Piel de Oveja",
    back_to_catalog: "Volver al Catálogo",
    description: "Descripción",
    default_description: "El {product} refleja la esencia de la filosofía de design minimalista de {designer}. Creado con materiales de primera calidad y un enfoque en los detalles esenciales, ofrece un estilo atemporal y una comodidad excepcional.",
    select_size: "Seleccione un Tamaño",
    quantity: "Cantidad",
    add_to_bag: "Añadir a la Bolsa",
    add_to_favorites: "Añadir a Favoritos",
    added_to_favorites: "Ir a favoritos",
    proceed_to_checkout: "Proceder al Checkout",
    free_shipping: "Envío gratis en pedidos superiores a $100.",
    // Search bar
    search_placeholder: "productos, colores...",
    search_help: "Buscar...",
    greeting_morning: "¡Buenos días {name}!",
    greeting_afternoon: "¡Buenas tardes {name}!",
    greeting_evening: "¡Buenas noches {name}!",
    // Community Looks / ALTA
    ai_stylist_tagline: "Tu estilista personal de IA que realmente te entiende",
    create_your_own: "Crea el Tuyo",
    design_look_alta: "Diseña tu look perfecto con ALTA",
    shop_this_look: "Comprar Este Look",
    shop_the_look: "Comprar el Look",
    total_value: "Valor Total",
    add_entire_look: "Añadir Look Completo al Carrito",
    // Cart page
    shopping_bag: "Bolsa de Compras",
    bag_empty: "Tu bolsa de compras está vacía.",
    continue_shopping: "Continuar Comprando",
    item: "Artículo",
    total: "Total",
    move_to_wishlist: "Mover a Lista de Deseos",
    remove: "Eliminar",
    shipping_estimate: "Estimación de envío",
    calculated_at_checkout: "Calculado en el Checkout",
    duties_and_taxes: "Impuestos y aranceles",
    included: "Incluido",
    order_total: "Total del Pedido",
    add_popular_items: "Añade Estos Artículos Populares",
    // Cart footer
    secure_payment: "Pago Seguro",
    customer_care: "Atención al Cliente",
    location: "Ubicación",
    editorial_archive: "Archivo Editorial",
    careers: "Carreras",
    country_region: "País/Región: Brasil",
    email_signup: "Suscripción por E-mail",
    affiliates: "Afiliados",
    sitemap: "Mapa del Sitio",
    terms_conditions: "Términos y Condiciones",
    privacy_policy: "Política de Privacidad",
    cookies: "Cookies",
    accessibility: "Accesibilidad",
    // Checkout page
    checkout: "Pagar",
    checkout_email_prompt: "Ingresa tu correo electrónico para iniciar sesión o continuar como invitado.",
    email_address: "Dirección de correo electrónico",
    shipping_address: "Dirección de Envío",
    first_name: "Nombre",
    last_name: "Apellido",
    street_address: "Dirección",
    company_optional: "Empresa (Opcional)",
    city: "Ciudad",
    zip_code: "Código Postal",
    country_region_label: "País/Región",
    state_province: "Estado/Provincia",
    phone: "Teléfono",
    shipping_method: "Método de Envío",
    free_shipping_eligible: "Tu pedido califica para envío gratis.",
    standard_shipping: "Envío Estándar",
    business_days: "3-5 días hábiles",
    free: "Gratis",
    payment_method: "Método de Pago",
    credit_debit_card: "Tarjeta de Crédito / Débito",
    secure_payment_note: "Todas las transacciones son seguras y encriptadas.",
    card_number: "Número de Tarjeta",
    name_on_card: "Nombre en la Tarjeta",
    expiration_date: "Fecha de Vencimiento (MM/AA)",
    security_code: "Código de Seguridad (CVV)",
    order_summary: "Resumen del Pedido",
    items_label: "Artículos",
    cart_empty: "Tu carrito está vacío.",
    only_remaining: "Solo queda 1",
    subtotal: "Subtotal",
    shipping_total: "Total de Envío",
    place_order: "Realizar Pedido",
    live_assistance: "Asistencia en Vivo",
    order_placed: "¡Pedido realizado con éxito!",
    // Footer help links
    shipping: "Envío",
    returns: "Devoluciones",
    contact: "Contacto",
    // Onboarding
    onboarding_luxury: "Curaduría de lujo. Acceso restringido.",
    onboarding_request_access: "Solicitar Acceso",
    onboarding_take_quick_tour: "Hacer un recorrido rápido 💫",
    onboarding_already_member: "Ya soy un miembro ♟️",
    onboarding_first_name_title: "Ingresa tu primer nombre ✍️",
    onboarding_first_name_desc: "Esto se usará para personalizar tu curaduría.",
    onboarding_first_name_placeholder: "Primer nombre",
    onboarding_continue: "Continuar",
    onboarding_lang_title: "Idioma preferido",
    onboarding_lang_desc: "¿Cómo debemos comunicarnos contigo?",
    scroll_to_explore: "DESLIZA PARA EXPLORAR",
    onboarding_style_title: "Perfil de Estilo 👤",
    onboarding_style_desc: "{name}, ¿cómo prefieres tu ajuste?",
    onboarding_male: "Masculino",
    onboarding_female: "Femenino",
    onboarding_both: "Ambos",
    onboarding_hunt_title: "La Búsqueda 🔍",
    onboarding_hunt_desc: "Y {name}, ¿qué es lo que más te llama la atención?",
    onboarding_brand_title: "Afinidad de Marca 💎",
    onboarding_brand_desc: "Cuéntame, ¿cuáles de estas te gustan más?",
    onboarding_email_title: "¡Genial! Ahora guarda tu correo y contraseña!",
    onboarding_email_desc: "Para asegurar tu perfil y solicitar acceso.",
    onboarding_email_placeholder: "Correo electrónico",
    onboarding_password_placeholder: "Contraseña",
    onboarding_analyzing: "Analizando perfil...",
    onboarding_curating: "Curando catálogo exclusivo...",
    onboarding_printing: "Imprimiendo tu pase...",
    onboarding_ticket_presents: "Villaoro presenta",
    onboarding_ticket_edition: "Catálogo privado",
    onboarding_ticket_admit: "Acceso único",
    onboarding_ticket_footnote: "Acceso de miembro",
    onboarding_ticket_guest: "Invitado",
    // ---- Onboarding: lo que dicen los miembros (texto provisional) ----
    testimonials_eyebrow: "En sus palabras",
    testimonials_title: "Lo que dicen los miembros.",
    testimonial_1_meta: "Miembro desde 2024",
    testimonial_1_body: "Dejé de recorrer miles de anuncios casi idénticos. Todo lo que hay aquí es algo que de verdad me pondría, y eso ya cambió mi forma de comprar.",
    testimonial_2_meta: "São Paulo",
    testimonial_2_body: "Pregunté por el calce antes de pedir y me respondió alguien que tenía la pieza en la mano. No es a lo que estoy acostumbrada.",
    testimonial_3_meta: "Miembro desde 2023",
    testimonial_3_body: "El precio de la ficha era el precio final, y la pieza llegó tal como se describía. Sin sorpresas, algo más raro de lo que debería.",
    testimonial_4_meta: "Lisboa",
    testimonial_4_body: "Catálogo pequeño, estándar alto. He comprado cuatro piezas y sigo usando todas, lo que dice más que cualquier puntuación.",
    testimonial_5_meta: "Miembro desde 2025",
    testimonial_5_body: "Pedí un lunes, seguí el envío esa misma semana y lo llevé el fin de semana. Todo discreto y simplemente funcionó.",
    testimonial_6_meta: "Milán",
    testimonial_6_body: "Lo que me convenció fue lo que no hay: sin filas patrocinadas, sin descuentos falsos. Alguien decidió que cada pieza debía estar, y se nota.",
    onboarding_approved: "Acceso Aprobado",
    onboarding_welcome_club: "Bienvenido al club,",
    onboarding_verify_title: "Verifica tu Correo Electrónico",
    onboarding_verify_desc1: "Hemos enviado un enlace de verificación a",
    onboarding_verify_desc2: "Por favor revisa tu bandeja de entrada (y carpeta de spam) para verificar tu cuenta antes de iniciar sesión.",
    onboarding_redirecting: "Redirigiendo a iniciar sesión...",
    install_app_title: "Villaoro en tu Pantalla de Inicio",
    install_app_subtitle: "Convierte Villaoro en una aplicación ✨",
    install_step1_title: "1. Abre las opciones del navegador",
    install_step1_desc: "Haz clic en compartir. Si no tienes esta opción, haz clic en los tres puntos (⋮).",
    install_step2_title: "2. Haz clic en Añadir o Instalar",
    install_step2_desc: "Selecciona 'Añadir a Pantalla de Inicio' o 'Instalar aplicación'.",
    install_step3_title: "3. Confirma para finalizar",
    install_step3_desc: "Confirma el nombre y haz clic en 'Añadir' o 'Instalar' para crear el acceso directo.",
    tour_step1_title: "Búsqueda y Filtros",
    tour_step1_desc: "Encuentra lo que deseas rápidamente con la barra de búsqueda, color grading o selector de marcas.",
    tour_step2_title: "Detalles del Producto",
    tour_step2_desc: "Haz clic en cualquier producto para ver más fotos, tallas y añadirlo a Favoritos.",
    tour_step3_title: "Categorías",
    tour_step3_desc: "Desliza y selecciona para descubrir los diferentes tipos de artículos que tenemos para ti.",
    product_tour_step1_title: "Descripción del Producto",
    product_tour_step1_desc: "Aquí encontrarás todos los detalles, materiales y el estilo de esta pieza.",
    product_tour_step2_title: "Añadir a Favoritos",
    product_tour_step2_desc: "Haz clic aquí para marcar este artículo como favorito y continuar con el pedido 📫✨",
    tour_next: "Siguiente",
    tour_done: "Hecho",
    install_app_tip: "💡 Consejo: La opción 'Instalar aplicación' abre el sitio a pantalla completa. En iOS, si no ves la opción en Chrome, usa Safari.",
    install_app_continue: "Continuar",
    // Quick tour — catalogue preview
    tour_preview_eyebrow: "Un primer vistazo",
    tour_preview_title: "Este es tu catálogo",
    tour_preview_subtitle: "Cada pieza elegida a mano, renovada cada semana. Sigue bajando.",
    // Sign in
    login_title: "Bienvenido de nuevo",
    login_subtitle: "Entra en tu espacio curado.",
    login_cta: "Acceder",
    login_forgot_password: "¿Olvidaste tu contraseña?",
    login_reset_sending: "Enviando...",
    login_reset_sent: "Enlace de restablecimiento enviado. Revisa tu correo.",
    login_reset_needs_email: "Escribe tu correo primero y te enviaremos un enlace de restablecimiento.",
    login_no_account: "¿Aún no tienes una cuenta?",
    login_success: "¡Bienvenido de nuevo!",
    login_error_credentials: "El correo o la contraseña no coinciden. Inténtalo de nuevo.",
    login_error_unconfirmed: "Verifica tu correo antes de acceder. Revisa tu bandeja de entrada.",
    login_error_generic: "Algo salió mal. Inténtalo de nuevo.",
    login_show_password: "Mostrar contraseña",
    login_hide_password: "Ocultar contraseña",
    login_back: "Atrás",
  }
};

const commonTerms: Record<string, Record<string, string>> = {
  PT: {
    retro: "retrô",
    khaki: "caqui",
    black: "preto",
    white: "branco",
    brown: "marrom",
    blue: "azul",
    green: "verde",
    red: "vermelho",
    navy: "marinho",
    grey: "cinza",
    gray: "cinza",
    leather: "couro",
    suede: "camurça",
    cotton: "algodão",
    silk: "seda",
    wool: "lã",
    cashmere: "cashmere",
    sneakers: "tênis",
    shoes: "sapatos",
    boots: "botas",
    slides: "chinelos",
    sandals: "sandálias",
    bag: "bolsa",
    tote: "tote",
    belt: "cinto",
    hat: "chapéu",
    cap: "boné",
    bracelet: "pulseira",
    necklace: "colar",
    ring: "anel",
    gold: "ouro",
    silver: "prata",
    edition: "edição",
    original: "original",
    originals: "originals",
    classic: "clássico",
    with: "com",
    buckles: "fivelas",
    stitch: "stitch",
    triple: "triplo",
    soft: "macio",
    embossed: "relevo",
    croc: "crocodilo",
    ankle: "cano curto",
    crewneck: "gola careca",
    sweater: "suéter",
    polo: "polo",
    jacket: "jaqueta",
    flight: "aviador",
    shearling: "pele de carneiro",
    trimmed: "com acabamento",
    blouson: "blusão",
    reversible: "reversível",
    outerwear: "agasalho",
    bonded: "colado",
    nylon: "nylon"
  },
  ES: {
    retro: "retro",
    khaki: "caqui",
    black: "negro",
    white: "blanco",
    brown: "marrón",
    blue: "azul",
    green: "verde",
    red: "rojo",
    navy: "marino",
    grey: "gris",
    gray: "gris",
    leather: "cuero",
    suede: "gamuza",
    cotton: "algodón",
    silk: "seda",
    wool: "lana",
    cashmere: "cachemira",
    sneakers: "zapatillas",
    shoes: "zapatos",
    boots: "botas",
    slides: "sandalias",
    sandals: "sandalias",
    bag: "bolso",
    tote: "tote",
    belt: "cinturón",
    hat: "sombrero",
    cap: "gorra",
    bracelet: "pulsera",
    necklace: "collar",
    ring: "anillo",
    gold: "oro",
    silver: "plata",
    edition: "edición",
    original: "original",
    originals: "originals",
    classic: "clásico",
    with: "con",
    buckles: "hebillas",
    stitch: "stitch",
    triple: "triple",
    soft: "suave",
    embossed: "relieve",
    croc: "cocodrilo",
    ankle: "botín",
    crewneck: "cuello redondo",
    sweater: "suéter",
    polo: "polo",
    jacket: "chaqueta",
    flight: "aviador",
    shearling: "piel de oveja",
    trimmed: "con ribete",
    blouson: "cazadora",
    reversible: "reversible",
    outerwear: "ropa de abrigo",
    bonded: "unido",
    nylon: "nailon"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("villaoro_lang");
    if (saved === "PT" || saved === "ES" || saved === "EN") return saved;

    // Auto-detect browser language
    const browserLang = navigator.language.split("-")[0].toUpperCase();
    if (browserLang === "PT") return "PT";
    if (browserLang === "ES") return "ES";
    return "EN";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("villaoro_lang", lang);
  };

  const t = (key: string) => {
    // 1. Check for exact match in full dictionary
    if (translations[language][key]) {
      return translations[language][key];
    }

    // 2. Smart Translate Fallback: Translate common words if no exact match
    if (language !== "EN" && key && typeof key === 'string' && key.includes(" ")) {
      // For Romance languages (PT, ES), the noun usually comes before the adjective.
      // E.g., "Black Cotton Polo" -> "Polo Cotton Black".
      // This simple reversal heuristic significantly improves the readability of untranslated products.
      let words = key.split(" ");
      if (language === "PT" || language === "ES") {
        words = words.reverse();
      }

      const translatedWords = words.map(word => {
        // Extract leading and trailing punctuation
        const match = word.match(/^([^a-zA-Z0-9]*)(.*?)([^a-zA-Z0-9]*)$/);
        if (!match) return word;

        const [, prefix, coreWord, suffix] = match;
        const lowerWord = coreWord.toLowerCase();
        const translated = commonTerms[language][lowerWord];

        if (translated) {
          // Preserve capitalization if original word was capitalized
          let finalTranslated = translated;
          if (coreWord.length > 0 && coreWord[0] === coreWord[0].toUpperCase()) {
            finalTranslated = translated.charAt(0).toUpperCase() + translated.slice(1);
          }
          return `${prefix}${finalTranslated}${suffix}`;
        }
        return word;
      });

      return translatedWords.join(" ");
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className="transition-opacity duration-500 ease-in-out">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
